### ISSUE TITLE
Question: Do you plan any docs for this great repository?

### ISSUE THREAD

**Issue by ArturJS** [impulse/react-hooks-mobx-state-tree#66]
## Question: Do you plan any docs for this great repository?
If you wouldn't mind I can add some basic setup which will describe API info akin to, say, https://effector.now.sh/

**Comment by ArturJS** [comment]
And when it's possible could you publish it to https://www.npmjs.com/package/react-hooks-mobx-state-tree ?
Thank you in advance!

**Comment by ecklf** [comment]
Hey @ArturJS,

`mobx-state-tree` already has official docs here: https://mobx-state-tree.js.org/intro/philosophy

As for the npm package, someone seems to have published this already https://www.npmjs.com/package/mobx-store-provider thus I don't see a reason to make one that does the same thing.

**Comment by ArturJS** [comment]
@impulse 
Wow, thanks a lot for the hint!
Closing as a resolved 😃
